### ISSUE TITLE
Battery optimization does not work consistently.

### ISSUE THREAD

**Issue by saravananmnm** [Bhat015/optimize_battery#4]
I have installed optimize_battery: ^0.0.4 plugin in android OS 10,11 and 12. 
battery optimization gets enabled after 2 hours or so in all the above OS. 
Any suggestion for resolving the problem is highly appreciated.

**Comment by Bhat015** [comment]
Sounds strange.
Are you reinstalling the app? this will cause the reset of optimization settings for the app.

**Comment by saravananmnm** [comment]
/MethodChannel#optimize_battery(26375): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#optimize_battery(26375): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(:164)
E/MethodChannel#optimize_battery(26375): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.notImplemented(:248)
E/MethodChannel#optimize_battery(26375): 	at c.c.a.a.onMethodCall(:66)
E/MethodChannel#optimize_battery(26375): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(:233)
E/MethodChannel#optimize_battery(26375): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(:84)
E/MethodChannel#optimize_battery(26375): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(:865)
E/MethodChannel#optimize_battery(26375): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#optimize_battery(26375): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#optimize_battery(26375): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#optimize_battery(26375): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#optimize_battery(26375): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#optimize_battery(26375): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#optimize_battery(26375): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/DartMessenger(26375): Uncaught exception in binary message listener
E/DartMessenger(26375): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(26375): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(:164)
E/DartMessenger(26375): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(:253)
E/DartMessenger(26375): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(:84)
E/DartMessenger(26375): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(:865)
E/DartMessenger(26375): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/DartMessenger(26375): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/DartMessenger(26375): 	at android.os.Looper.loop(Looper.java:183)
E/DartMessenger(26375): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/DartMessenger(26375): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(26375): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/DartMessenger(26375): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by ghadeerAbdulmajeed** [comment]
hello i've got this error No implementation found for method isIgnoringBatteryOptimizations on channel optimize_battery)
any thoughts ?
